on: push

name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build_css
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
        run:
          - npm run css:build

      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          ENV: prod
          GA_ANALYTICS_ID: G-81B4LEX9Y8
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
